/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type LineText = string | LineSegment[];
export type LineSegment = string | RichSegment;

export interface BookFormat {
  conditions: ConditionItem[];
  conversations: ConversationItem[];
  lines: LineItem[];
  nouns: NounItem[];
  projectName: string;
  roles: RoleItem[];
  rooms: RoomItem[];
  verbs: VerbItem[];
  [k: string]: unknown;
}
export interface ConditionItem {
  description?: string | null;
  id: string;
  num: number;
  parentRoom: number;
  [k: string]: unknown;
}
export interface ConversationItem {
  condition?: number | null;
  id: string;
  parentNoun: number;
  verb?: number | null;
  [k: string]: unknown;
}
export interface LineItem {
  id: string;
  num: number;
  parentConversation: number;
  role: number;
  talker_num: number;
  text: LineText;
  [k: string]: unknown;
}
export interface RichSegment {
  style: RichStyle;
  text: string;
  [k: string]: unknown;
}
export interface RichStyle {
  bold: boolean;
  italic: boolean;
  [k: string]: unknown;
}
export interface NounItem {
  description?: string | null;
  id: string;
  is_cutscene: boolean;
  num: number;
  parentRoom: number;
  [k: string]: unknown;
}
export interface RoleItem {
  id: string;
  name: string;
  raw: string;
  shortName: string;
  [k: string]: unknown;
}
export interface RoomItem {
  id: string;
  name?: string | null;
  num: number;
  [k: string]: unknown;
}
export interface VerbItem {
  id: string;
  name: string;
  num: number;
  [k: string]: unknown;
}
