/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GameScript {
  conversations: {
    [k: string]: Conversation;
  };
  nouns: {
    [k: string]: Noun;
  };
  roles: {
    [k: string]: Role;
  };
  rooms: {
    [k: string]: Room;
  };
  [k: string]: unknown;
}
export interface Conversation {
  cond?: string | null;
  conv_id: number;
  lines: Line[];
  noun: string;
  verb?: string | null;
  [k: string]: unknown;
}
export interface Line {
  id: string;
  role: string;
  text: RichText;
  [k: string]: unknown;
}
export interface RichText {
  items: TextPiece[];
  [k: string]: unknown;
}
export interface TextPiece {
  style?: TextStyle;
  text: string;
  [k: string]: unknown;
}
export interface TextStyle {
  bold: boolean;
  italic: boolean;
  [k: string]: unknown;
}
export interface Noun {
  conversations: string[];
  noun_id: number;
  noun_name?: string | null;
  noun_title: RichText;
  room_id: string;
  [k: string]: unknown;
}
export interface Role {
  name: string;
  short_name: string;
  [k: string]: unknown;
}
export interface Room {
  nouns: string[];
  room_id: number;
  room_title: RichText;
  [k: string]: unknown;
}
